void print_arr(int [], int);
int max(int [], int);
int min(int [], int);
int find(int [], int, int);
void sort(int [], int);
void swap(int *, int *);
void swapc(char *, char *);
void reverse(int *, int);
void reversec(char *, int);
double avg(int [], int);
void Bub_sort(int arr[], int len);
void sel_sort(int arr[], int len);
void ins_sort(int arr[], int len);
//可变数组结构体
struct list{
    char **data;
    int size;
    int capacity;
};
void init(struct list *l);
void change_capacity(struct list *l);
void check_capacity(struct list *l);
int size(struct list *l);
char* get(struct list *l, int index);
void add(struct list *l, char *value);
void insert(struct list *l, int index, int value);
void delete(struct list *l, int index);
void display(struct list *l);
void fini(struct list *l);
int find_nnull(struct list *l);